# Node.js React Web App on Linux
# Build a Node.js React app and deploy it as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
#

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '282bf220-8943-485c-abaf-187252d34b78'

  # Web app name
  webAppName: 'react-spa'

  # Agent VM image name
  vmImageName: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'
  
  # for Jest
  CI: true

stages:
- stage: Build
  displayName: Docker Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x

    steps:
    - script: |
        npm install
      displayName: npm install
    - script: |
        npm test
      displayName: npm test
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/junit.xml'
      inputs:
        testResultsFiles: '**/junit.xml'

      condition: always()

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: ikeike443ACR-connection
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: react_spa
        tags:
          tag1
